#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

runApplication blockMesh
runApplication setSolidFraction
runApplication transformPoints "rotate=((0 1 0) (0 0 1))"

# Decompose domain for 8 processors
decomposePar -force

# Run laserbeamFoam in parallel on 8 processors
mpirun -np 8 laserbeamFoam -parallel

# run DEM manually before the simulation if needed
