#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Verify it's picking your local mpirun
which mpirun
mpirun --version

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

runApplication blockMesh
runApplication setFields
decomposePar
mpirun --oversubscribe -np 16 laserbeamFoam -parallel
reconstructPar
