# Check the laserbeamFoam solvers compile correctly
name: Build

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        container-image:
          - name: "OpenFOAM-10"
            image: "openfoam/openfoam10-paraview56:latest"
            source: "/opt/openfoam10/etc/bashrc"
            buildflags: "-j"

    container:
      image: ${{ matrix.container-image.image }}
      options: --user root

    steps:
      - uses: actions/checkout@v4


      - name: Allwmake
        shell: bash -l {0}
        run: |
          source ${{ matrix.container-image.source }}
          ./Allwmake ${{ matrix.container-image.buildflags }}

      - name: Alltest
        shell: bash -l {0}
        run: |
          source ${{ matrix.container-image.source }}
          cd tutorials
          ./Alltest
