# Check formatting of markdown files
name: Markdown Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run MarkdownLint
        uses: DavidAnson/markdownlint-cli2-action@v18.0.0
        with:
          globs: "documentation/**/*.md,imported/**/*.md,installation/**/*.md,README.md,about/**/*.md,tutorials/**/*.md,support/**/*.md"
          separator: ','
